version: 2
jobs:
  build-and-test:
    environment:
      IMAGE_NAME: tomaka/cargo-apk
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
  publish-docker-image:
    environment:
      IMAGE_NAME: tomaka/cargo-apk
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish final image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_LOGIN --password-stdin
            docker push $IMAGE_NAME
  publish-crates-io:
    working_directory: ~/android-rs-glue
    environment:
      IMAGE_NAME: tomaka/cargo-apk
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run: cd ./cargo-apk && cargo publish --token $CRATESIO_TOKEN
      - run: cd ./glue && cargo publish --token $CRATESIO_TOKEN
workflows:
  version: 2
  all:
    jobs:
      - build-and-test
      - publish-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - publish-crates-io:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
